import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const production = process.argv[2] === "production";
const watch = process.argv[2] === "--watch";

const context = await esbuild.context({
	banner: {
		js: "/* THIS FILE IS GENERATED BY ESBUILD. */"
	},
	bundle: true,
	entryPoints: ["src/main.ts"],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	logLevel: "info",
	minify: production,
	outfile: "main.js",
	platform: "browser",
	sourcemap: production ? false : "inline",
	target: "es2018",
	treeShaking: true
});

if (watch) {
	await context.watch();
} else {
	await context.rebuild();
	await context.dispose();
}
